version: 2

jobs:
  build:
    docker:
      - image: rustlang/rust:nightly-slim
    steps:
      - checkout
      - run:
          name: Version information
          command: rustc --version; cargo --version; rustup --versionj
      - run:
          name: Print the Current Time
          command: echo $CIRCLE_TAG
      - run:
          name: execute script
          command: ./scripts/demo.sh
